### ISSUE TITLE
Needs new maintainer(s) and coordinated effort

### ISSUE THREAD

**Issue by aspiers** [aspiers/mysqldiff#14]
It no longer makes sense for me to maintain this project:

- I've been doing a terrible job of maintainership for a few years already
- I have zero interest in hacking Perl any more these days (sorry but Ruby and Python are *so* much nicer)
- I don't use MySQL / MariaDB much
- There seem to be technically superior alternatives around, such as https://dev.mysql.com/doc/mysql-utilities/1.6/en/mysqldiff.html and the whole [ActiveRecord](http://guides.rubyonrails.org/active_record_basics.html) ecosystem.

However, it seems that some people still find it useful.  So I should do the responsible thing and hand over maintainership.  Obvious candidates are @estrabd, @vitaliy-evsyukov (a.k.a. @guyfawkes), @rurban, and @posbit.  However it's a bit concerning to see that [you guys all seem to be working on the same codebase apparently without coordinating efforts at all](https://github.com/aspiers/mysqldiff/network), so you're probably all wasting time duplicating effort on fixing the same issues.  Does anyone want to volunteer to take over maintainership and ideally merge efforts?

Thanks!

**Comment by estrabd** [comment]
I'm happy to coordinate the effort. Monday I'll get my repo up to date and will begin going over all the PRs.

Any objection to this?

Thanks for your past work and maintainership, Adam.

Brett

**Comment by aspiers** [comment]
Sounds great, thanks! As you can see from https://github.com/aspiers/mysqldiff/network there seem to have been quite a lot of commits made to private forks.  It would be great if those could all be merged into the same place.

**Comment by estrabd** [comment]
Yeah, my first order of business will be to get all those in. I guess there is no real handoff, just that my fork starts getting used as the main one?

**Comment by rurban** [comment]
Given that  @guyfawkes mostly does PHP, I'm pretty busy, and I don't know @posbit, but I do know @estrabd, I think @estrabd is the best choice.

**Comment by aspiers** [comment]
Awesome, thanks guys!  @estrabd I could simply give you push access to my fork - that would save having to worry about breaking links scattered all over the web.

**Comment by estrabd** [comment]
Thanks for the vote @rurban =)... @aspiers that sound good to me.

**Comment by estrabd** [comment]
@aspiers let me know when I can start committing =)

**Comment by aspiers** [comment]
@estrabd Now :-)

**Comment by estrabd** [comment]
Thanks!
