### ISSUE TITLE
Let's move the website to a GH hosted page

### ISSUE THREAD

**Issue by estrabd** [aspiers/mysqldiff#19]
@aspiers any chance you can get this moved over at some point?

https://pages.github.com/

If not, I'll get to it; I'd just need you to add a redirect or link at http://adamspiers.org/computing/mysqldiff/ to the new location.

**Comment by aspiers** [comment]
Absolutely, I was thinking of the same thing!  I can definitely add a redirect when it's ready.  I guess all you need to do is create a `gh-pages` branch, right?

**Comment by aspiers** [comment]
If it helps, I can click the "Launch Automatic page generator" button.

**Comment by estrabd** [comment]
I had to use the google cache to get the source of the page, but I got it up at:

http://aspiers.github.io/mysqldiff/

I didn't grab the css or images, so if you wouldn't mind checking out the "gh-pages" branch and getting those assets into there, I'd appreciate.

Thank!

**Comment by aspiers** [comment]
I'd strongly recommend we ditch the current "design" (or lack of) and go with something more modern.  Don't feel you have to just clone the original page, since it was made in a totally different era of the web :)

**Comment by aspiers** [comment]
P.S. why did you need to use the google cache?

**Comment by estrabd** [comment]
I was only going to modify the page for info, but I imagine at some point it might get a facelift. But to answer your question, going to http://software.adamspiers.org/wiki/mysqldiff gives me a "Page not found".

**Comment by aspiers** [comment]
Ohhh I see.  But it's the exact same content as http://adamspiers.org/computing/mysqldiff/ so I thought you had got it from there.

**Comment by estrabd** [comment]
Calling this done. http://aspiers.github.io/mysqldiff/
