### ISSUE TITLE
Finalize Changes, roll distro and release on CPAN.

### ISSUE THREAD

**Issue by estrabd** [aspiers/mysqldiff#20]

**Comment by estrabd** [comment]
@aspiers when I get this done, I was going to upload it to PAUSE myself - http://search.cpan.org/~estrabd. 

Any objection to this?

**Comment by aspiers** [comment]
No objection! Thanks!

**Comment by estrabd** [comment]
I plan on getting a new release out during YAPC::NA 2016 - in a couple of weeks. I will spend time hacking on this while there.

**Comment by estrabd** [comment]
trial version, http://www.cpan.org/authors/id/E/ES/ESTRABD/MySQL-Diff-0.44-TRIAL.tar.gz - rolled via Dist::Zilla

**Comment by estrabd** [comment]
Final step, going to QA before I submit release.

**Comment by estrabd** [comment]
releasing as .46.

https://github.com/aspiers/mysqldiff/pull/26
