### ISSUE TITLE
Pasword characters problem

### ISSUE THREAD

**Issue by eusonlito** [aspiers/mysqldiff#22]
Using mysql with `&` simbol on password returns error:

> mysqldiff --host1="domain.com" --user1="db1" --password1='lAA64&7' --port1="3306" --host2="domain.com" --user2="db2" --password2="FsASSmU" --port2="3306" db:"db1" db:"db2"

```
Warning: Using a password on the command line interface can be insecure.
Errors from mysqldump:
sh: 1: 7: not found
mysqldiff cannot get diff because of this errors
```

**Comment by aspiers** [comment]
Sounds like the `&` character in the password is leaking into a `system` command or similar, which is really bad.  Taint mode would probably help here.

**Comment by estrabd** [comment]
Thank you, @eusonlito. I too a brief look, and I think that more fundamentally, we need to look at using the list variant of the system command.  I'll investigate a fix, unless someone wants to issue a PR in the meantime. I don't think taint mode is going to help us here.

**Comment by aspiers** [comment]
> we need to look at using the list variant of the system command

Exactly!

> I don't think taint mode is going to help us here.

I meant that it would help identify the source of the problem, not that it would fix the problem.

**Comment by eusonlito** [comment]
Hello! Any news about this problem?

Thanks!

**Comment by estrabd** [comment]
No ETA, I would like to take a look at this soon. Thanks for following up.

**Comment by estrabd** [comment]
slated for after 0.44 release

**Comment by estrabd** [comment]
Hopefully solved by https://github.com/aspiers/mysqldiff/pull/28 ...
