### ISSUE TITLE
I need permission on PAUSE to release new version of MySQL::Diff

### ISSUE THREAD

**Issue by estrabd** [aspiers/mysqldiff#27]
@aspiers please see below. I'm eager to get this pushed. Thanks!

> The following report has been written by the PAUSE namespace indexer.
> Please contact modules@perl.org if there are any open questions.
> 
>   User: ESTRABD (B. Estrade)
>   Distribution file: MySQL-Diff-0.46.tar.gz
>   Number of files: 28
>   *.pm files: 4
>   README: MySQL-Diff-0.46/README
>   META-File: MySQL-Diff-0.46/META.yml
>   META-Parser: Parse::CPAN::Meta 1.4414
>   META-driven index: no
>   Timestamp of file: Tue Jun 21 16:08:16 2016 UTC
>   Time of this run: Tue Jun 21 16:09:50 2016 UTC
> 
> This distribution name will only be indexed when uploaded by users with
> permission for the package MySQL::Diff. Either someone else has
> ownership over that package name, or this is a brand new distribution
> and that package name was neither listed in the 'provides' field in the
> META file nor found inside the distribution's modules. Therefore, no
> modules will be indexed.
> 
> 
> Further details on the indexing attempt follow.
> 
> The following packages (grouped by status) have been found in the distro:
> 
> Status: Permission missing
> ==========================
> 
>      module : MySQL::Diff
>      version: 0.46
>      in file: MySQL-Diff-0.46/lib/MySQL/Diff.pm
>      status : Not indexed because permission missing. Current registered
>              primary maintainer is ASPIERS. Hint: you can always find
>              the legitimate maintainer(s) on PAUSE under "View
>              Permissions".
> 
>      module : MySQL::Diff::Database
>      version: 0.46
>      in file: MySQL-Diff-0.46/lib/MySQL/Diff/Database.pm
>      status : Not indexed because permission missing. Current registered
>              primary maintainer is ASPIERS. Hint: you can always find
>              the legitimate maintainer(s) on PAUSE under "View
>              Permissions".
> 
>      module : MySQL::Diff::Table
>      version: 0.46
>      in file: MySQL-Diff-0.46/lib/MySQL/Diff/Table.pm
>      status : Not indexed because permission missing. Current registered
>              primary maintainer is ASPIERS. Hint: you can always find
>              the legitimate maintainer(s) on PAUSE under "View
>              Permissions".
> 
>      module : MySQL::Diff::Utils
>      version: 0.46
>      in file: MySQL-Diff-0.46/lib/MySQL/Diff/Utils.pm
>      status : Not indexed because permission missing. Current registered
>              primary maintainer is ASPIERS. Hint: you can always find
>              the legitimate maintainer(s) on PAUSE under "View
>              Permissions".
> 
> __END__

**Comment by aspiers** [comment]
Should be fixed now!

**Comment by estrabd** [comment]
tag 0.47 pushed, should be on CPAN soon thanks!
