### ISSUE TITLE
Adding auto increment column fails with error 1075

### ISSUE THREAD

**Issue by mikeraynham** [aspiers/mysqldiff#30]
Two statements are used to add an AUTO_INCREMENT primary key column, and this causes a 1075 error: `Incorrect table definition; there can be only one auto column and it must be defined as a key`

For example, the diff to go from this:

```sql
CREATE TABLE `my_table` (
  `email_address` varchar(320) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

...to this:

```sql
CREATE TABLE `my_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email_address` varchar(320) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

...contains these two statements:

```sql
ALTER TABLE my_table ADD COLUMN id int(10) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE my_table ADD PRIMARY KEY (id);
```

The correct statement in this case is:

```sql
ALTER TABLE my_table ADD COLUMN id int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY;
```

**Comment by estrabd** [comment]
Thank you, will put it on my radar.

**Comment by estrabd** [comment]
Accepted PR https://github.com/aspiers/mysqldiff/pull/32
