### ISSUE TITLE
Build.PL not equivalent to Makefile.PL, prereq String::ShellQuote missing

### ISSUE THREAD

**Issue by andk** [aspiers/mysqldiff#31]
As per subject. Grep:

http://search.cpan.org/grep?release=MySQL-Diff-0.47;string=String::ShellQuote;n=1;C=0

Sample file report:

http://www.cpantesters.org/cpan/report/0666efcc-3889-11e6-97e3-01f96608a794

HTH&&Thanks,

**Comment by estrabd** [comment]
Thank you, will put it on my radar.

**Comment by estrabd** [comment]
There was an old Build.PL laying around as an artifact of the old method of creating a release. I've removed this and created a new release, hopefully this will take care of the issue you've reported. Thanks!
