### ISSUE TITLE
Run mysqldump in --single-transaction

### ISSUE THREAD

**Issue by SilentScope** [aspiers/mysqldiff#33]
First of all - great script - very useful!

I only found an issue when running it - that DB is blocked for a short time - what is not very good to use it in production environment.

I would like to request for a fix: use the InnoDB specific --single-transaction when launching mysqldump. I think this option could be passed as a parameter.

Thanks!

**Comment by SilentScope** [comment]
I just examined the code and see that possibily best option would be to allow the user to specify --single-transaction option and to pass it directly to mysqldump command.

**Comment by estrabd** [comment]
Thanks for the PR, will review soonish. Any chance can create a test?

**Comment by SilentScope** [comment]
Thanks, I will try to write test as well, but the change is really trivial.

**Comment by estrabd** [comment]
That's fine. I'll get it merged as long as it doesn't break existing tests. New release to follow.
Thank you

**Comment by estrabd** [comment]
merged

**Comment by SilentScope** [comment]
Great - when to expect it to be released?

**Comment by estrabd** [comment]
Now, just uploaded it to PAUSE. It might take a little while so keep checking.
