### ISSUE TITLE
Operator expected at /usr/local/bin/mysqldiff line 213, near ""single-transaction|S" "list-tables|l""

### ISSUE THREAD

**Issue by SilentScope** [aspiers/mysqldiff#36]
String found where operator expected at /usr/local/bin/mysqldiff line 213, near ""single-transaction|S" "list-tables|l""
	(Missing operator before  "list-tables|l"?)
syntax error at /usr/local/bin/mysqldiff line 213, near ""single-transaction|S" "list-tables|l""
Execution of /usr/local/bin/mysqldiff aborted due to compilation errors.

**Comment by estrabd** [comment]
Thank you.

**Comment by estrabd** [comment]
0.50 has been sent to PAUSE, now it's just a matter of time.
