### ISSUE TITLE
Use of uninitialized value in pattern match

### ISSUE THREAD

**Issue by ninglianjie** [aspiers/mysqldiff#42]
index 'abc' removed
Use of uninitialized value in pattern match (m//) at /usr/local/share/perl5/MySQL/Diff.pm line 434.

**Comment by ninglianjie** [comment]
index adc(abc)

table1 had field 'abc'
field 'abc' removed
index 'abc' removed
Use of uninitialized value in pattern match (m//) at /usr/local/share/perl5/MySQL/Diff.pm line 434.

**Comment by estrabd** [comment]
@ninglianjie why did you close this issue?

**Comment by ninglianjie** [comment]
@estrabd 
https://github.com/ninglianjie/mysqldiff/commit/b50b4ba6e0c0a8ebcac0e8421f72a36d418c0062 #__
